### ISSUE TITLE
Add NX Workspace 

### ISSUE THREAD

**Issue by jordanpowell88** [nestjs-addons/in-memory-db#88]
Our e2e tests keep failing in the CI pipeline. After talking to @wesleygrimes we think it might make most sense to add NX Workspace to help manage these dependencies.

**Comment by wesleygrimes** [comment]
Notes from meeting 10/3

- Create an app for each package
- Package.json will have a separate run/build/test command for each package
- The plan will be to test migrating and publishing with in-memory-db first
- Document how to create a new package (what is involved in doing this? create a schematic for it?)

**Comment by DominikPieper** [comment]
Can I get this one?

**Comment by wesleygrimes** [comment]
> Can I get this one?

Sure thing! As part of this work I would like to address the following:

- Currently this repo is setup to release on every commit merged using `semantic-release`, I would like more control over what commits are included in a release (so that I can batch them)
- I would like the ability to release beta or next versions to npm
- Maybe you can look into the publishable/buildable lib concept in nx

**Comment by DominikPieper** [comment]
The publishable libs where what I thought about. Not sure but I think it would be a good idea to split the e2e into devapp and tests?

**Comment by wesleygrimes** [comment]
> The publishable libs where what I thought about. Not sure but I think it would be a good idea to split the e2e into devapp and tests?

That makes sense to me

**Comment by DominikPieper** [comment]
Initial PR on the platform repo. Not all done yet, but a start

**Comment by wesleygrimes** [comment]
Done! Thanks for being the catalyst for this @DominikPieper!
 https://github.com/nestjs-addons/platform
